server:
  port: 3007
  env: development

database:
  host: 161.132.50.183
  port: 5432
  user: postgres
  password: jtorres159.
  name: auth
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: 5m

rabbitmq:
  url: amqp://jtorres:jtorres159.@161.132.50.183:5672
  exchange: microservices
  queue: auth_service

auth:
  jwt_secret: P1HJBGFUv2X8YoVEjSQR3cawTLAKDgNm # Cambia esto por una cadena secreta segura
  token_expiration: 24h